### ISSUE TITLE
syntax error at or near \"$1\"\n\n>

### ISSUE THREAD

**Issue by coolmonster** [ForbesLindesay/atdatabases#152]
I am getting syntax errors while using select queries using this library. can you please look into this
` const { tableName } = req.query;

      const tableData = await req.app
        .get('db')
        .query(sql`select * from ${tableName}`);`
i am encountering following error
`{"type":"error","message":"syntax error at or near \"$1\"\n\n> 1 | select * from $1\n    |               ^^\n","error":{"length":91,"name":"error","severity":"ERROR","code":"42601","position":"15","file":"scan.l","line":"1150","routine":"scanner_yyerror"}}`

**Comment by nmaves** [comment]
This is a DB limitation.  You can't use query params for table names.

**Comment by DeeLindesay** [comment]
Have you tried using `sql.ident`?
```
query(sql`SELECT * from ${sql.ident(tableName)}`);
 ```
 
 This works for me.
