### ISSUE TITLE
Unable to use Postgres Anonymous Code Block syntax

### ISSUE THREAD

**Issue by clafollett** [ForbesLindesay/atdatabases#164]
The @databases/pg packages do not support parsing file or SQLQuery text containing PG Anonymous Code Block syntax (i.e. `$<optional_tag>$ ... $<optional_tag>$`): https://www.postgresql.org/docs/12/plpython-do.html.

This syntax is common with structures like DO and PROCEDURE for defining the internal code definition. Lack of this support makes it impossible to deploy PROCEDURES, FUNCTIONS, DO blocks, etc since each of these require internal commands delimited with ";". Please consider adding this functionality. Please advise if this functionality is already supported.

**Comment by ForbesLindesay** [comment]
#170 is the same issue, so this will be fixed along with that.
