### ISSUE TITLE
Multiple Instances of Dockerized Postgres databases

### ISSUE THREAD

**Issue by eloquia** [ForbesLindesay/atdatabases#178]
First of all, this is a great library you've developed--it's made us a lot more productive.

I have this use-case where I have two REST API projects, each having their own repos and set of database tables. We developed them separately because they each cover a different domain. Now we've come to a point in development where we'd like to do some local integration testing, and both projects use `@databases/pg-test/.../globalSetup` and every time we try to run the second instance of `pg-test` locally, it kills the first container. Fortunately both projects use different Postgres Schemas, so I'm not terribly concerned. I changed the Postgres driver port numbers on one project, but I'm still having no luck

I was wondering what my options were for running two projects at the same time which each use `pg-test`? I suppose I could:

* Copy & paste the migrations & seeders file so that I only need to run `pg-start` on one project and still be able to run separate REST APIs without issue
* Define a Kubernetes configuration file that would EITHER
    * run one database in one Docker container and run both sets of migrations/seeders in that one container OR
    * run two databases in two different Docker containers and define a Kubernetes bridge network
* Maybe I'm missing something in `@databases` that would allow me to run two containers at the same time?

**Comment by ForbesLindesay** [comment]
If you specify a different `port` and `containerName` for each project, they should be able to run independently. This can be set using:

```json
{
  "test": {
    "port": 5460,
    "containerName": "project-a"
  }
}
```

in your pg config (e.g. `.pgrc.json`)

**Comment by dalecb13** [comment]
Thanks for responding, this resolved my issue.
