### ISSUE TITLE
Documentation references files (globalSetup.js & globalTeardown.js) that don't exists

### ISSUE THREAD

**Issue by N8ers** [ForbesLindesay/atdatabases#185]
### The issue
I'm going through the [Postgres Testing with Node.js](https://www.atdatabases.org/docs/pg-test) docs. In the `Jest` section it says to add this to the jest configs

```js
globalSetup: "<rootDir>/node_modules/@databases/pg-test/jest/globalSetup.js",
globalTeardown: "<rootDir>/node_modules/@databases/pg-test/jest/globalTeardown.js",
```

However there is no `globalSetup.js` or `globalTeardown.js` file in that directory. 

![at_database_screenshot](https://user-images.githubusercontent.com/29260938/130230738-1573f991-a77e-4903-ac71-9d153e3f5382.png)

If you have an answer I'd be happy to do a PR against the docs!

**Comment by N8ers** [comment]
Modifying the `jest.config.js` to the below fixed my problem.

```js
const config = {
  verbose: true,
  globalSetup:
    "<rootDir>/node_modules/@databases/pg-test/lib/jest/globalSetup.js",
  globalTeardown:
    "<rootDir>/node_modules/@databases/pg-test/lib/jest/globalTeardown.js",
};

module.exports = config;
```

**Comment by ForbesLindesay** [comment]
The `.js` suffix should have been removed. The docs are now fixed.
