### ISSUE TITLE
Expose table name publicly inside pg-typed Table

### ISSUE THREAD

**Issue by avaly** [ForbesLindesay/atdatabases#187]
Currently the `Table` instances from `pg-typed` don't expose the actual `tableName` publicly: https://github.com/ForbesLindesay/atdatabases/blob/master/packages/pg-typed/src/index.ts#L220

In certain cases, especially when you need to build a complex SQL query using JOINs, you might want to access the table names from the Table instances themselves. Something like this:

```ts
sql`
  SELECT *
  FROM ${Foo.tableName}
  JOIN ${Bar.tableName} ON ${Bar.tableName}.id = ${Foo.tableName}.id
`
```

I can submit a PR for this change.

**Comment by ForbesLindesay** [comment]
Sounds good to me 👍
