### ISSUE TITLE
Error: Jest: Got error running globalSetup

### ISSUE THREAD

**Issue by droganov** [ForbesLindesay/atdatabases#188]
Hi, it looks that documented `@databases/pg-test` setup is not stable

From time to time I get the following error:

```
Error: Jest: Got error running globalSetup - .../api-server/node_modules/@databases/pg-test/lib/jest/globalSetup.js, reason: npm run migrate exited with code 1:
could not connect to postgres: Error: Connection terminated unexpectedly
    at Connection.<anonymous> (.../api-server/node_modules/pg/lib/client.js:132:73)
```

It looks the connection attempt starts before the container is actually up.

As a workaround we pause the migrations a bit, but it appears that the situation should be solved on a library level with some sort of observer that is pinging the database port unless it opens or timeout fires.

**Comment by ForbesLindesay** [comment]
Thank you for reporting this and sorry for the delayed response. I believe it should be fixed in [`@databases/pg-test@3.1.1`](https://github.com/ForbesLindesay/atdatabases/releases/tag/%40databases%2Fpg-test%403.1.1)
