### ISSUE TITLE
Syntax error at or near "$1" while setting run-time parameters

### ISSUE THREAD

**Issue by mashaklimkin** [ForbesLindesay/atdatabases#194]
Dynamically setting a run-time parameter using `sql.value()` throws an error in `@databases/pg`:

```JavaScript
sql`SET app.param = ${sql.value(param)};`
```

results in `syntax error at or near "$1"`.
My `@databases/pg` version is 5.1.1.

Workaround:

```JavaScript
sql`SELECT set_config('app.param', ${sql.value(param)}, FALSE);`
```

**Comment by ForbesLindesay** [comment]
This just means Postgres doesn't accept query parameters in that location. You can hard code the values as sql strings, or try sql.ident if Postgres expects an identifier: https://www.atdatabases.org/docs/sql#sql-ident

if all else fails, you can use "dangerous raw value" to run arbitrary sql https://www.atdatabases.org/docs/sql#sql-__dangerous__rawvalue
