### ISSUE TITLE
How can I catch database connection errors?

### ISSUE THREAD

**Issue by tukusejssirs** [ForbesLindesay/atdatabases#200]
Sorry for a newbie question but how can I catch the following errors:
- `error: the database system is shutting down`;
- `terminating connection due to administrator command`;
- `Timed out waiting for connection from pool`.

I’d like to configure my app to wait for the DB server for to restart (if it restarts) and timeout after `n` seconds. This is related to the first two errors above.

If the connection pool is full, I think I could use `queueTimeoutMilliseconds` option, but please confirm this.

Anyway, I use PostgreSQL 13.4 if that is important.

**Comment by ForbesLindesay** [comment]
It should only cause the given query to fail, rather than crashing the entire app, so you could do something like:

```typescript
import createConnectionPool, {sql} from '@databases/pg';
// ...or...
// const createConnectionPool = require('@databases/pg');
// const sql = require('@databases/pg').sql;

const database = createConnectionPool();

async function waitForDatabaseConnection() {
  while (true) {
    try {
      await database.query(sql`SELECT 1 + 1`);
      return
    } catch (ex) {
      console.error(ex.message);
      console.error(`Retrying in one second...`);
      await new Promise(r => setTimeout(r, 1000));
    }
  }
}

waitForDatabaseConnection().then(() => {
  // Database connection is ready for you to use in the rest of your app,
  // so `import` or `require` the rest of your app code here.
}).catch(ex => {
  console.error(ex.stack);
  process.exit(1);
});
```
