### ISSUE TITLE
mysql-test: missing support for `arm64` (macOS M1 / Apple Silicon) 

### ISSUE THREAD

**Issue by AmitMY** [ForbesLindesay/atdatabases#214]
After installing docker, the error is:
> Unable to parse: 
Pulling Docker Image mysql:8.0.23
Error: Jest: Got error running globalSetup - /node_modules/@databases/mysql-test/lib/jest/globalSetup.js, reason: docker pull mysql:8.0.23 exited with code 1:
no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by ForbesLindesay** [comment]
I'd be happy to update the default docker image if there is a version of the official `mysql` image that supports arm64

**Comment by AmitMY** [comment]
Thanks @ForbesLindesay 

It would be able to emulate the behavior. if `arm64` is detected, add `platform` flag.

```sh
docker pull --platform linux/amd64 mysql:8.0.23
```
Instead of 
```sh
docker pull mysql:8.0.23
```
