### ISSUE TITLE
mysql: parsing TIMESTAMP field with null default result in error

### ISSUE THREAD

**Issue by mcollina** [ForbesLindesay/atdatabases#221]
If you define a schema like:

```sql
CREATE TABLE pages (
  id SERIAL PRIMARY KEY,
  title VARCHAR(42),
  inserted_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL
)
```

You'll get the error:

```
Error: Expected yyyy-mm-dd HH:MM:SS
    at handleError (/home/matteo/repositories/XXX/node_modules/@databases/mysql/src/MySqlDriver.ts:266:25)
    at executeQueryInternal (/home/matteo/repositories/XXX/node_modules/@databases/mysql/src/MySqlDriver.ts:246:5)
    ...
```

Because in the parsing of datetimes, `null` is not considered a valid value.

I can send a PR if you'd like. In case I would return a JS `null` whenever that is detected.

**Comment by ForbesLindesay** [comment]
Yes, if you can add a test case that would currently fail, and fix the date parsing so it doesn't fail, I'd happily accept that Pull Request. If I don't see the PR, feel free to ping me on twitter `@ForbesLindesay` to request a review.

**Comment by mcollina** [comment]
The PR is in!
