### ISSUE TITLE
Question: Capability of browser and esm

### ISSUE THREAD

**Issue by PorcoRosso85** [ForbesLindesay/atdatabases#311]
Hi, forks.

https://www.atdatabases.org/docs/sql
{ sql } module is capable for browser and esm?

I want it to be used on browser
like this:

```
<script>
import { sql } from "@databases/sql"

const query = sql`...`
</script>

```

**Comment by ForbesLindesay** [comment]
You can use the package from the browser via:

```ts
import sql from '@databases/sql/web';
```

The `/web` export excludes the `sql.file` utility as that would not work in the browser, but it's otherwise fully functional.

You will need to use something like webpack to bundle your code though.
