### ISSUE TITLE
Build Standalone CLI for pg-migrations

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/atdatabases#34]
[pg-migrations](https://github.com/ForbesLindesay/atdatabases/tree/master/packages/pg-migrations) isn't really useable at the moment as it lacks a CLI. It is currently a work in progress porting over from [@moped/db-pg-migrations](https://github.com/mopedjs/moped/tree/master/packages/db-pg-migrations) which was run via the global [moped CLI](https://github.com/mopedjs/moped/blob/master/packages/scripts/src/scripts/db.ts). The moped CLI assumes the package will be bundled via webpack. This is an option, but I suspect we will be better off with something like `ts-node`.

I think the tasks are approximately:

- [ ] Document the API for people building non-CLI migrations runners. The closest we have to existing documentation are the tests. The new docs should go in the [docs folder](https://github.com/ForbesLindesay/atdatabases/tree/master/docs) so they create pages on the website.
- [ ] Swap `camelCase` in table/field names for `snake_case`, using `camelCase` is odd and makes things look like they're not really native to postgres.
- [ ] Build a CLI. This can be loosely based on the mongo one, but should use a combination of CLI flags, env vars and pg-config for any configuration options. It should prompt for any inputs it needs that are not configured properly (unless run in CI). It should support up all, down all, up one down one, down last, up a specific migration, down a specific migration and toggle the state of a specific migration without actually running it.
- [ ] Document the CLI tool

Once this is complete, we'll want to investigate how we port this to MySQL and ideally share code with MySQL.

**Comment by Sharaal** [comment]
If it helps you: https://github.com/Sharaal/sql-pg/wiki/Migrations and https://github.com/Sharaal/sql-pg/blob/master/bin/migrate.js :) 

I was also not happy with the current solutions of the available migration tools.
