### ISSUE TITLE
Automatically Generate Types from Database queries

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/atdatabases#39]
I would like to be able to automatically generate types from the database queries. To do this:

- [ ] Build an SQL parser that is flexible in how it handles placeholders that could be replaced with other SQL, and which supports a reasonable subset of the postgres/mysql/sqlite syntax - being worked on in #20
- [ ] Write util to extract queries from typescript files
- [ ] Write util to extract type from parsed SQL query and database schema
- [ ] Tie everything together in an awesome CLI

**Comment by stevenmiller888** [comment]
Re the SQL parser - ideally it supports the entire grammar for each dialect. I built https://github.com/stevenmiller888/ts-mysql-parser for the language service plugin, on top of Antlr4 with the grammar extracted from MySQL workbench. The beauty of it is that you can specify the version you want. Working with Antlr4 was a pretty pleasant experience btw, and it looks like they have a full grammar ready-to-go for [sqlite](https://github.com/antlr/grammars-v4/tree/master/sql).

Re extracting types - not sure exactly what you mean but maybe this is related: https://github.com/nettofarah/mysql-schema-ts.

**Comment by ForbesLindesay** [comment]
The pg-typed/mysql-typed approach seems to have worked well enough here to cover 99% of the use case. I no longer think it's a worthwhile idea right now to attempt to generate types from raw SQL queries.
