### ISSUE TITLE
Exchange escaping loop with a RegExp replace for identifiers

### ISSUE THREAD

**Issue by Sharaal** [ForbesLindesay/atdatabases#56]
For escaping identifiers loops are used which are not that pretty/optimised and can be easily exchanged by a RegExp replace.

So here: 
https://github.com/ForbesLindesay/atdatabases/blob/master/packages/sql/src/SQLQuery.ts#L402-L411

Use:
```javascript
return '"' + str.replace(/"/g, '""') + '"'
```

Similar also for the MySQL identifier escaping here: https://github.com/ForbesLindesay/atdatabases/blob/master/packages/sql/src/SQLQuery.ts#L437-L446

**Comment by ForbesLindesay** [comment]
Thank you for the suggestion. I've made some optimisations to identifier escaping in #223. The `.spit(x).join(x+x)` approach was marginally faster when I tested, and felt like a cleaner implementation here. More importantly, most identifiers in most code bases don't include quotes, so a simple short-circuit that just checks for the existence of a quote character results in a really significant performance boost here.
