### ISSUE TITLE
Connection does not seem to be terminated

### ISSUE THREAD

**Issue by obourne** [ForbesLindesay/atdatabases#67]
When running the example code connecting to local mysql database https://www.atdatabases.org/docs/mysql it connects and queries fine but the node process doesn't automatically terminate so I have to use ctrl-c to do it. In other libraries like `mysql` you need to call `connection.end()`, I can't see that in this library but I tried `db.dispose()` and that failed saying there were no connections.

There may be doing something I'm doing wrong here but I compared the behaviour against the `mysql` module and that terminates fine. I prefer the interface to this library so would be interested in using it but at the moment don't have the confidence to do so.

**Comment by cdock1029** [comment]
wondering about this as well, if the connection should be closed

**Comment by ForbesLindesay** [comment]
`db.dispose()` should work fine. Can you try:

```js
const connect = require('@databases/mysql');
const {sql} = require('@databases/mysql');

const db = connect();

db.query(sql`SELECT 1 + 41;`).then(
  results => console.log(results),
).then(() => db.dispose()).catch(err => {
  console.error(err);
  process.exit(1);
});
```

That's working for me, and exiting cleanly.

If that works for you, could you submit a pull request to update the examples for pg and mysql:

- https://github.com/ForbesLindesay/atdatabases/blob/master/docs/pg.md
- https://github.com/ForbesLindesay/atdatabases/blob/master/docs/mysql.md

**Comment by obourne** [comment]
Thanks for you response and sorry for the delay in mine, I will look into this next week and get back to you.
